spring:
  application:
    name: lease-api
  datasource:
    url: jdbc:mysql://localhost:3306/lease?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: Xuyc7791.
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update
    generate-ddl: true
  data:
    redis:
      host: localhost
      port: 6379
      database: 0
      connect-timeout: 5s
      timeout: 5s

minio:
  endpoint: http://localhost:9000
  access-key: daie
  secret-key: 12345678
  bucket-name: lease
